### ISSUE TITLE
Type error with Puppet v4 parser

### ISSUE THREAD

**Issue by riton** [jhoblitt/puppet-udev#20]
With the latest version of puppetserver, we encounter the following error:

```
Evaluation Error: Error while evaluating a Function Call, 
Module udev is not supported on RedHat release 7 at /etc/puppetlabs/code/environments/production/modules/udev/manifests/params.pp:42:13
```

We've tested that the error fades away if we _cast_ operatingsystemmajrelease to either _string_ or _integer_.

**Comment by jhoblitt** [comment]
@riton / @nexecook I've added a beaker acceptance tests on centos 7 to the travis matrix that is passing.  Is this error still reproducible?  Odd that the problem would be puppetserver specific.

**Comment by nexecook** [comment]
I can't reproduce it anymore.

**Comment by jhoblitt** [comment]
OK -- it may have been a puppetserver and/or facter version specific thing.  I'm going to close this ticket but if anyone can reproduce this, please reopen the issue.
